// Code generated by 'yaegi extract github.com/Autumn-27/ScopeSentry/internal/utils'. DO NOT EDIT.

package symbols

import (
	"github.com/Autumn-27/ScopeSentry/internal/utils"
	"reflect"
)

func init() {
	Symbols["github.com/Autumn-27/ScopeSentry/internal/utils/utils"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DeleteFile":   reflect.ValueOf(utils.DeleteFile),
		"DownloadFile": reflect.ValueOf(utils.DownloadFile),
		"EnsureDir":    reflect.ValueOf(utils.EnsureDir),
		"Marshal":      reflect.ValueOf(utils.Marshal),
		"Unmarshal":    reflect.ValueOf(utils.Unmarshal),
		"WriteFile":    reflect.ValueOf(utils.WriteFile),
	}
}
